language: node_js
cache: yarn
jobs:
  include:
    - stage: build
    - script: yarn build
    - stage: deploy
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master
          
stages:
  - build
  - test
  - deploy
